### ISSUE TITLE
確認画面のBGM切替ボタンについて

### ISSUE THREAD

**Issue by sugiosugio** [hitorec/hitorec#42]
<img width="903" alt="スクリーンショット 2020-03-30 15 29 23" src="https://user-images.githubusercontent.com/58411645/77882395-dd81f380-729b-11ea-910e-1ca2b064630c.png">

確認画面のBGM切替ボタンについて、
デザインと仕様を上記のように変更する予定です。
※タップの反応範囲は「♫BGM」ラベル含めたサムネイル内の右上を想定

作業の進め方はどのようにするのがいいでしょうか？？
こちらも録音時のPermissionダイアログ同様に、
フォントサイズやマージン等のデザイン調整ができればと思っています！

**Comment by pannpers** [comment]
@sugiosugio

**Comment by sugiosugio** [comment]
@pannpers 
了解です！

**Comment by pannpers** [comment]
## 変更点
- 今の `cool` の音源を `シンプル` に名前変更。
- 今の `simple` の音源を `relax` に名前変更。
- ラベルの順番は変えないので、BGMの切り替え順は下記のようになる
  1. `cool`
  1. `pop`
  1. `relax`

**Comment by pannpers** [comment]
@sugiosugio ちょいと相談レベルなのですが、
ユーザーが『BGM切り替えボタン』を見たときに『押したらBGMを切り替えることができる』ということに気が付かない可能性があるかな〜と思いました！例えば、下記のようなちょっとした修正を入れると、より分かりやすいUIになる気がします！

- 初回アクセス時に チュートリアル（ボタンがフォーカスされて、軽いナビゲーションメッセージを表示する）を入れる。
- 押したら切り替わりそうなアイコンを使う。
