### ISSUE TITLE
hitoRec一覧画面のサムネイル画像について

### ISSUE THREAD

**Issue by sugiosugio** [hitorec/hitorec#54]
現状、hitoRec一覧画面のサムネイル画像に固定の画像を入れてもらっていますが（こちらの指示です）、
やはり実際のタイトル入りサムネイル画像のほうがメリットがあるように感じるので、
シェア時に生成されるタイトルの入りサムネイル画像を表示する仕様に変更お願いいたします！

**Comment by pannpers** [comment]
@sugiosugio こちら承知しましたー！
