### ISSUE TITLE
録音画面タイトル入力ボックスへの改行文字入力について

### ISSUE THREAD

**Issue by sugiosugio** [hitorec/hitorec#57]
録音画面のhitoRecタイトル入力ボックスへの
改行文字入力を不可にする仕様にしたいと思います。（JSで制御する形ですかね？）

録音後のサムネイル生成時に除去することもできると思いますが、
テキストボックスの表示が崩れた状態を見せてしまうのはクオリティに関わるので、
入力自体できない＆コピペされたら直ちに除去する仕様にしたいです！

**Comment by pannpers** [comment]
@sugiosugio 確かにそうですね！
