### ISSUE TITLE
動画サムネイルの生成と適用

### ISSUE THREAD

**Issue by pannpers** [hitorec/hitorec#68]
# Overview
入力されたタイトル文字列をもとに動画の背景画像となるサムネイルを生成したい。
生成した画像は、収録確認画面とアーカイブ一覧画面でも使用される。

# To-Do

- [x] タイトル文字列をもとにHTML Element を作成し、それをキャプチャして画像にする。
- [x] 生成した画像をCloud Storageに保存する。
- [x] 保存した画像のStorageパスをFirestoreに保存する。
- [x] Twitter投稿時に画像をダウンロードして、動画の背景画像として使用する。

# Notes
[hitorec/prd\.md at master · hitorec/hitorec](https://github.com/hitorec/hitorec/blob/master/docs/prd.md#10-mockups-or-prototypes%E3%83%A2%E3%83%83%E3%82%AF%E3%81%BE%E3%81%9F%E3%81%AF%E3%83%97%E3%83%AD%E3%83%88%E3%82%BF%E3%82%A4%E3%83%97)

**Comment by pannpers** [comment]
@sugiosugio 以前、作って頂いたサムネイル用のHTML、CSS、JSを `src` ディレクトリの下に置いてもらっても良いでしょうか？

**Comment by pannpers** [comment]
@sugiosugio 一旦、サムネイルの生成と動画への適用はできるようになったのですが、いくつか課題が残っているのでこちらにメモを残しておきます。


HRMLのDOMからPNG画像への変換は https://github.com/bubkoo/html-to-image というライブラリを使っているのですが、内部処理で CSS をダウンロードする際に下記のようなエラーが出ております。そのため、指定したWebフォントが画像内のテキストには適用されていません。

> Error while reading CSS rules from https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,500,700&display=swap SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

![image](https://user-images.githubusercontent.com/5513309/105626439-ea975100-5e72-11eb-818d-964c8afd8f61.png)

---

また、上記のライブラリがオリジナルのDOMのスタイルを厳密に解析してくれないため、 `font-size` や `margin` あたりが微妙にズレた画像が生成されてしまいます。現状では、こちらは明確なソリューションが見つけられておらず、ズレに合わせてCSSを調整する必要がありそうです。ちなみにCSSは下記のファイルに記載しております。

https://github.com/hitorec/hitorec/blob/master/src/resources/elements/hr-thumbnail.html

**Comment by sugiosugio** [comment]
確認しました！

まず前提として、Twitterタイムライン上でサムネイルは重要になる「顔」の部分なので、もっとも妥協したくない部分ですね〜。サムネイルのデザインは、ある意味Webサイトのデザインよりも重要だと思っているので、現状は別のライブラリで回避できないか？ということを探る方向性で考えたいです。（ひとまずベータ版は泣く泣く妥協するという方向はあり）

あと、1点気になっている点として、サムネイルに使用しているフォントはAdobeフォント（dnp-shuei-mgothic-std）ですが、エラーはgoogleフォントになっています。これはどういう理由ですかね？まぁAdobeフォントでも同様のエラーは出そうですが。。
